### ISSUE TITLE
No need to wait after Wire.requestFrom()

### ISSUE THREAD

**Issue by Koepel** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#1]
In the file "SparkFun_Si7021_Breakout_Library.cpp", in the function "makeMeasurment()", there is a delay and timeout after Wire.requestFrom(). That delay and timeout are not needed. There is nothing to wait for.

When the Wire.requestFrom returns, the I2C transaction has completely finished and the received data is waiting in a buffer in the Wire library. The Wire.read() reads data from that buffer.

**Comment by JoelEB** [comment]
Fixed and tagged.
