### ISSUE TITLE
Compatibility with Uno R4

### ISSUE THREAD

**Issue by santaimpersonator** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#11]
* **Wire object**
  > * Pass Wire in as a stream object into the library
  
  As mentioned in [another issue](https://github.com/sparkfun/SparkFun_Si7021_Arduino_Library/issues/10#issue-1119799506), being able to pass the Wire object would make the library compatible with the Qwiic connector on the new Uno R4.
* **Returned values**
  The values returned from the libary using the Weather shield seemed off. The default code works with the Uno **R3**; However, the returned values are off when used with the Uno **R4**. I even tested a few of the example sketches from this library and pressure seems to return with `-999`.
  
  Using the `SparkFunMPL3115A2SimpleSketch.ino` was yeilding the following values forom the Serial Monitor:
  
      Pressure(Pa): -999 Temp(f): -1766.20
      Pressure(Pa): -999 Temp(f): -1766.20
      Pressure(Pa): -999 Temp(f): -1766.20
      Pressure(Pa): -999 Temp(f): -1766.20

  * I haven't investigated the problem with the returned values thoroughly yet, but it may becoume a larger issue as more people transition to the Uno R4.

**Comment by nseidle** [comment]
This should be fixed in v2 of the library.
