### ISSUE TITLE
Errror during compiling because of ambiguous handover in line 203

### ISSUE THREAD

**Issue by gsimon54** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#12]
SparkFun_Si7021_Breakout_Library.cpp
line 191:
**uint8_t** nBytes = 3; //changed from  uint16_t --> uint8_t due to avoid compile error by calling function Wire.requestFrom(ADDRESS,nBytes)!!!!!!!

**Comment by nseidle** [comment]
This should be fixed in v2 of the library.
