### ISSUE TITLE
'Weather' does not name a type

### ISSUE THREAD

**Issue by giorgiogallina** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#14]
Dear developer,
Since the new release **2.0.0**, an error is raised when trying to intancing a variable of type Weather. This did not happen with version **1.0.5**.
`Compilation error: 'Weather' does not name a type; did you mean 'matherr'?`
Thank you for your work.

**Comment by nseidle** [comment]
This library no longer uses the word 'weather' so I don't know how there is a compilation error with that result. I suspect you are using older code. Please try running example 1 and let us know if you continue to have problems.
