### ISSUE TITLE
Reading error in makemeasurement function

### ISSUE THREAD

**Issue by myke239** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#3]
I was using this library with a Ti CC3200 dev board similar to a launch pad and encountered an issue where all the values were returned were always the same constant negative number. I looked through the library and found the issue in the makemeasurement function that is used to write and read from the registries.

`	Wire.beginTransmission(ADDRESS);
	Wire.write(command);
	Wire.endTransmission();
	// When not using clock stretching (*_NOHOLD commands) delay here
	// is needed to wait for the measurement.
	// According to datasheet the max. conversion time is ~22ms
	 delay(100);

	Wire.requestFrom(ADDRESS,nBytes);
	if(Wire.available() != nBytes)
  	return 100;`

The reason I was getting that value was because device did not see any available bytes and would return 100. I found the issue was because there was no delay between the `Wire.requestFrom(ADDRESS,nBytes);` line and the `if(Wire.available() != nBytes)` line. (perhaps this only happens on devices with higher clock speeds)

After reading the sensors datasheet based on the comments in the code above, I realized the delay should be after the` Wire.requestFrom()` but before checking if bytes are available, in order to take into account the delay of the sensor responding.

After doing that I had no issues.
That section of code should be:
```
	Wire.beginTransmission(ADDRESS);
	Wire.write(command);
	Wire.endTransmission();

        uint32_t start = millis();
        while(Wire.requestFrom(ADDRESS,nBytes) < nBytes ){
             if(millis()  - start > 2000) break;
        }

        delay(25);
	if(Wire.available() != nBytes)
  	return 100;

	unsigned int msb = Wire.read();
	unsigned int lsb = Wire.read();
        uint32_t chksum = Wire.read();
```

Hope this helps someone out!

**Comment by nseidle** [comment]
Thanks for reporting **a long time ago**. Fixed in v2 of the library.
