### ISSUE TITLE
The Weather::begin() function returns no value

### ISSUE THREAD

**Issue by marksidell** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#8]
The Weather:begin() function is declared to return a bool, presumably to indicate success/failure. But it returns no value.

**Comment by nseidle** [comment]
Thanks for reporting. Fixed with PR #5.

**Comment by marksidell** [comment]
I added a comment to the PR. You need braces around the two indented statements at the bottom of the function.

**Comment by marksidell** [comment]
You are correct, but indenting the return makes the code confusing to read. The indentation implies that you intended to include the two statements in a block but forgot to.

**Comment by nseidle** [comment]
Totally agree with you, it looks terrible, but it works. Additionally, there is a pile of problems with this repo (should not do a Wire.begin in begin(), should not Serial print in a library, mis-named library and files, et al). If you feel like tackling this or any other issue you see I welcome a PR.

**Comment by marksidell** [comment]
I would like to help. I can try a clean-up and submit a PR.
