### ISSUE TITLE
makeMeasurement failures aren't propogated correctly.

### ISSUE THREAD

**Issue by marksidell** [sparkfun/SparkFun_Si701_Breakout_Arduino_Library#9]
Weather::makeMeasurement() returns the magic value 100 if the wrong result is returned from the device. See https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library/blob/cbc0c5a625d09dfd3c891fa799c8fbc6cb61776f/src/SparkFun_Si7021_Breakout_Library.cpp#L205

The problem with this approach is that the magic value gets converted to some other value by the various get<x>() functions, which makes it difficult for a caller to know whether an error occurred. An alternative approach would be to define a "FAILURE" value that is outside the range of any real value, say 10000, and have all of the get<x>() functions check for that value and return it. Here is how I changed getRH():

```
#define SI7021_FAILED 10000
...

float Weather::getRH()
{
	// Measure the relative humidity
	uint16_t RH_Code = makeMeasurment(HUMD_MEASURE_NOHOLD);
	return RH_Code==SI7021_FAILED ? SI7021_FAILED  : (125.0*RH_Code/65536)-6;
}
```

**Comment by marksidell** [comment]
I should add that I'm generally pleased with the library, and am grateful that you wrote it and make it available.

**Comment by nseidle** [comment]
Awesome. Thanks for the kind words! 

I added a [list of changes](https://github.com/sparkfun/SparkFun_Si701_Breakout_Arduino_Library/issues/10) I'd like to see. WRT magic numbers: there are more than a few in there! Sorry about that. I agree with your approach. Adding an enum list of errors to the header file, that are values outside what the sensor is capable of returning, would allow us to internally check and pass codes around and improve readability.

**Comment by nseidle** [comment]
Just FYI: I've changed the repo name. Your git software should be ok with the change but don't be surprised if things are in limbo for a bit. Arduino has been notified but this will break library manager support until they resolve the name change (hopefully no more than a day or two).

**Comment by nseidle** [comment]
After some time spent on a plane, fixes are here!

Please see v2 of the library, specifically ex2. You can now call 

    if(getRH(&humidity) == true) {
      //Act on good reading
    }

getRH(float*) and getTemperature(float*) will return a bool if called with a pointer. If false, something went wrong.
